SOF-699 Support setting alternative_concept
olzzon/v-connection pull request #33
Opened 2022-02-08 14:01 UTC by LindvedKrvang

v-connection now supports to update the 'alternative_concept' entry on a playlist

2022-02-09 13:38 UTC, KvelaGorrrrnio commented on src/mse.ts
> +	private wrapInBracesIfNeeded(value: string): string {
Just a note: This does not have the exact same behaviour. E.g. `{somename` will become `{{somename}` (new way) instead of `{somename}` (old way).

2022-02-09 13:39 UTC, KvelaGorrrrnio commented on src/mse.ts
> +		const ALTERNATIVE_CONCEPT = 'alternative_concept'
Is there any reason that this is all caps?

2022-02-09 13:40 UTC, KvelaGorrrrnio approved these changes

2022-02-10 07:14 UTC, LindvedKrvang commented on src/mse.ts
> +		const ALTERNATIVE_CONCEPT = 'alternative_concept'
Yes, it was supposed to be a constant variable, just forgot to move it to the correct scope....
It has now been moved

2022-02-11 08:59 UTC, ianshade requested changes

2022-02-11 08:59 UTC, ianshade commented on src/v-connection.ts
> +	setAlternativeConcept(playlistID: string, concept: string): Promise<void>
I think this should be the concern of VRundown, because it manages the playlist - either the one it's given or the one it creates if no ID is provided. TSR doesn't need to know that ID and be forced to pass it.

2022-02-14 07:15 UTC, LindvedKrvang commented on src/v-connection.ts
> +	setAlternativeConcept(playlistID: string, concept: string): Promise<void>
Updated so VRundown now has the responsibility of setting the alternative concept

2022-02-15 09:42 UTC, ianshade commented on src/mse.ts
> +	private wrapInBracesIfNeeded(value: string): string {
I'll allow that. Having or not having both braces is conforming to different standards. Having only one brace is just user error.

2022-02-15 09:51 UTC, ianshade approved these changes
Well done! The version bump though, probably should be an effect of calling `yarn release` after merging.

2022-02-15 10:40 UTC, merged