SOF-1081 Only clean Shows that belongs to Sofie
olzzon/v-connection pull request #49
Opened 2022-11-08 13:09 UTC by LindvedKrvang

Only finds ShowIds for shows where the creator of the Elements is Sofie.
Update node version to 16.17.
Ignores the library "docs" when running lint.

2022-11-09 06:59 UTC, RasmusAlbrektsen approved these changes

2022-11-09 07:44 UTC, nytamin requested changes

2022-11-09 07:44 UTC, nytamin commented on src/rundown.ts
> +		return elements.find((element: FlatEntry) => element['creator'] === 'Sofie')
This should not be hard-coded to `"Sofie"` but instead reference the constant `CREATOR_NAME`.

2022-11-09 07:44 UTC, nytamin commented on src/rundown.ts
> +	async cleanupAllSofieShows(): Promise<CommandResult[]> {
Is there a reason the `cleanupAllShows` method is removed?
Since removing that would cause this to be a breaking change, could you instead leave it in and just add the new method to the side, or possibly just add an optional argument to only include Sofie shows?
```
- async cleanupAllShows(): Promise<CommandResult[]> {
+ async cleanupAllShows(onlySofie?: boolean): Promise<CommandResult[]> {
```

2022-11-09 07:44 UTC, nytamin commented on src/rundown.ts
> +		const pepResponseJS = await this.pep.getJS(`/storage/shows/${showId}/elements`, 1)
Isn't this quite similar what `listInternalElements` is doing? 
Perhaps it should be refactored to use that?

(If not, this method should at least include `await this.mse.checkConnection()` in the beginning)

2022-11-09 09:44 UTC, LindvedKrvang commented on src/rundown.ts
> +	async cleanupAllSofieShows(): Promise<CommandResult[]> {
I created `cleanupAllShows` a few weeks ago so it hasn't been rolled out yet.
It was a bit too aggressive for our usecase so I refactored it into `cleanupAllSofieShows` and I decided to "remove" `cleanupAllShows` because it is a new thing, so technically it is not a breaking change yet. 

But maybe this is some functionality you would like to use? If so, I can keep it there

2022-11-09 09:50 UTC, ianshade commented on src/rundown.ts
> +	async cleanupAllSofieShows(): Promise<CommandResult[]> {
@LindvedKrvang it has already been released in 6.1.0. Please use Conventional Commits and indicate breaking changes.

2022-11-09 09:51 UTC, LindvedKrvang commented on src/rundown.ts
> +		const pepResponseJS = await this.pep.getJS(`/storage/shows/${showId}/elements`, 1)
You're right. Had not seen that method. I will look into having less duplication.

I went with not calling `await this.mse.checkConnection()` since `isSofieShow()` is being used in a flow where that check has already been called. But since this is its own method there is nothing preventing me from using it in a flow where that check has yet to be called, so I will add it :)

2022-11-09 10:25 UTC, ianshade requested changes
Please adhere to Conventional Commits. We want a nice changelog in here.

2022-11-09 10:25 UTC, ianshade commented on src/rundown.ts
> +	}
It's called `mapToStringArray` as if it was quite a versatile method, but then it takes only `settledResultShowIds`.
And I'd never use `reduce` unless absolutelly needed, because it's just more complex and scary-looking than `filter` and `map`. Couldnt't all this be replaced by adding the following helper:
``` typescript
function isFulfilled<T>(settledResult: PromiseSettledResult<T>): settledResult is PromiseFulfilledResult<T> {
	return settledResult.status === 'fulfilled'
}
```
and then used like this 
``` typescript
settledResultShowIds.filter(isFulfilled).map((fulfilledResult) => fulfilledResult.value)
```
?

2022-11-09 12:20 UTC, LindvedKrvang commented
> Please adhere to Conventional Commits. We want a nice changelog in here.

Amended the commit message to begin with `feat!:`.
OBS: Since I had already pushed the commit I had to do a `git push --force-with-lease`. This will only be a problem if someone has pulled my branch and decides to push something from it without altering the commit.

2022-11-09 12:23 UTC, LindvedKrvang commented on src/rundown.ts
> +	async cleanupAllSofieShows(): Promise<CommandResult[]> {
Amended commit to include conventional commits

2022-11-09 12:23 UTC, LindvedKrvang commented on src/rundown.ts
> +		return elements.find((element: FlatEntry) => element['creator'] === 'Sofie')
Updated

2022-11-09 12:24 UTC, LindvedKrvang commented on src/rundown.ts
> +		const pepResponseJS = await this.pep.getJS(`/storage/shows/${showId}/elements`, 1)
`isSofieShow()` now uses `listInternalElemets()`

I had to do some minor changes to `listInternalElements()` since it would not populate the `creator` field

2022-11-09 13:13 UTC, LindvedKrvang commented on src/rundown.ts
> +	}
I see your point about the name. There is a philosophy where the parameter is implicit part of the name. For example it would be implicit that `mapToStringArray(value: number[])` would be "mapNumbersToStringArray".
But this is not really a philosophy we have been applying in Sofie.

I have updated the name to be `reduceSettledResultToShowIds()`.

Array.reduce() is neither scarier nor more complex than Array.map() and in most cases they are able to the same thing. Which one to choose largely comes down to which implementation is cleaner (and the preference of the developer).

I tried applying your suggestion, but the `.filter()` had a hard time parsing the `PromiseFulfilledResult` type along to the map, so I had to do the below code (and also change the type of `isFulfilled` to boolean instead)

```
return settledResultShowIds
			.filter(this.isFulfilled.bind(this))
			.map((value: PromiseSettledResult<string>) => (value as PromiseFulfilledResult<string>).value)
			.map(this.stripCurlyBrackets.bind(this))
```
(Not really sure why it wouldn't let me acces the `value` property without casting, when it had no problem letting me access it in the reduce implementation...)

Currently, I'm leaning slightly more towards the reduce approach for this implementation.

2022-11-10 06:22 UTC, LindvedKrvang commented on src/rundown.ts
> +	}
Here is a nice article about `.reduce()` if you are interested:
https://michelestieven.medium.com/in-defense-of-reduce-449b9b143933

2022-11-11 08:41 UTC, ianshade approved these changes

2022-11-11 08:47 UTC, KvelaGorrrrnio approved these changes

2022-11-11 08:53 UTC, merged